//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoAmIBotSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public long Id { get; set; }
        public string LangKey { get; set; }
        public string Name { get; set; }
        public int JoinTimeout { get; set; }
        public int GameTimeout { get; set; }
        public bool CancelgameAdmin { get; set; }
    }
}
